### ISSUE TITLE
self sign certificate generation requires package python-openssl

### ISSUE THREAD

**Issue by hlawatschek** [n0emis/ansible-role-bigbluebutton#10]
Please add the package python-openssl to the required package list for self signed certificates.

This is needed to prevent the following failure:

`TASK [n0emis.bigbluebutton : Generate an OpenSSL Certificate Signing Request] *****************************************************************************************************
fatal: [192.168.122.31]: FAILED! => {"changed": false, "msg": "Can't detect any of the required Python libraries cryptography (>= 1.3) or PyOpenSSL (>= 0.15)"}
`

**Comment by DO1JLR** [comment]
Or if you use python3 you need ``python-openssl`` :wink:

**Comment by DO1JLR** [comment]
thanks for fixing :heart:
