### ISSUE TITLE
systemd timer for video cache?

### ISSUE THREAD

**Issue by genofire** [n0emis/ansible-role-bigbluebutton#23]
Maybe it will be nice to have a systemd.timer (legacy cronjob) to clean the cache automatically.
https://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days

**Comment by BrutalBirdie** [comment]
@genofire could you check out the PR #96 there is an option which could add what you suggested.

**Comment by BrutalBirdie** [comment]
Solved by merging of #96
