### ISSUE TITLE
use |bool for binary values in this role

### ISSUE THREAD

**Issue by genofire** [n0emis/ansible-role-bigbluebutton#30]
warning appears if we use values like `ǹo` ...
https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#the-when-statement

**Comment by n0emis** [comment]
Hmm, I am not sure, since greenlight reqires lowercase letters, so I personally would rather choose `ternary("true", "false")`, although I don't know which would be the best/preferrable way to choose.

**Comment by genofire** [comment]
You are right, for templates and so on. I mean inside of ansible like here:

https://github.com/n0emis/ansible-role-bigbluebutton/blob/ef5665f7e9245cb8c8c1da7161135e9ac97559b8/tasks/main.yml#L67
