### ISSUE TITLE
Unable to activate greenlight email notifications

### ISSUE THREAD

**Issue by madmatah** [n0emis/ansible-role-bigbluebutton#49]
I did a fresh greenlight installation today and email notifications are not working anymore, even if I set  `bbb_allow_mail_notifications: true`.

The `.env` file generated by ansible contains :
```
[...]
ALLOW_MAIL_NOTIFICATIONS=True
[...]
```

And it is ignored by greenlight that expects a lowercase `true` value (see [here](https://github.com/bigbluebutton/greenlight/blob/51824ad84b398a8c1f5094427f40ab4b68ad33ed/config/application.rb#L90) and [here](https://github.com/bigbluebutton/greenlight/blob/11cdd1ec14cd41fb0f0d7d67acee1ba3bb8c315c/lib/tasks/configuration.rake#L32)).

**Comment by EdJoPaTo** [comment]
guess this is the same problem as #38 ?

**Comment by n0emis** [comment]
> guess this is the same problem as #38 ?

No, this is not. #39 was put in place as a fix for #38. This problem is related to #38.

**Comment by n0emis** [comment]
I have put a quickfix in place, although we maybe need to think about a better way as proposed in #30.
