### ISSUE TITLE
Cron to auto renew letsencrypt

### ISSUE THREAD

**Issue by singpolyma** [n0emis/ansible-role-bigbluebutton#50]
Like https://github.com/geerlingguy/ansible-role-certbot does

**Comment by 1977er** [comment]
Shouldn't that be already done by the certbot debian package?
There should be a /etc/cron.d/certbot which eventually fires a "certbot renew".

**Comment by toabi** [comment]
Yes, I just verified, there is a certbot cronjob and manually running `certbot renew` also lists the bbb cert as possible candidate for renewal.
