### ISSUE TITLE
CPUSchedulingPolicy is set in two tasks changing each other

### ISSUE THREAD

**Issue by EdJoPaTo** [n0emis/ansible-role-bigbluebutton#59]
When running two times in a row this should not change something (should be deterministic as much as possible)

Currently `CPUSchedulingPolicy` is set in two places and changing each other every time so there are changes.

https://github.com/n0emis/ansible-role-bigbluebutton/blob/54f7aa92e1c9a653d69e9e347a55760c3c65a3e9/tasks/main.yml#L33-L44

https://github.com/n0emis/ansible-role-bigbluebutton/blob/54f7aa92e1c9a653d69e9e347a55760c3c65a3e9/tasks/config.yml#L170-L188

As the second one is configurable I would think about removing the first one.
Also interesting to me, without having more knowledge into freeswitch currently: the first one does not notify freeswitch to restart as the second does so one of them is probably wrong.

**Comment by e1mo** [comment]
According to the README the CPUSchedulingPolicy is something related to containerized environments (LXC, Chroot). I think the first one could use a simple `when: bbb_cpuschedule`.
